# Generated by Django 5.1 on 2024-08-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_category_alter_product_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="catalog_photo/%Y/%m/%d/",
                verbose_name="фото",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products_photo/%Y/%m/%d/",
                verbose_name="фото",
            ),
        ),
    ]
